---

- name: set jail {{ jail_name }} autorun to 'run' on {{ hostname }}
  shell: ezjail-admin config -r run {{ jail_name | quote }}
  when: jail_autorun

- name: set jail {{ jail_name }} autorun to 'norun' on {{ hostname }}
  shell: ezjail-admin config -r norun {{ jail_name | quote }}
  when: not jail_autorun

- name: copy host's /etc/resolv.conf to jail {{ jail_name }}
  shell: cp -p /etc/resolv.conf /usr/jails/{{ jail_name | quote }}/etc/

...
