---

- name: check whether jail {{ jail_name }} exists on {{ hostname }}
  shell: ezjail-admin list | grep /usr/jails/{{ jail_name }} | wc -l | sed -e 's/^[ \t]*//'
  register: jail_exists

- name: check whether directory /usr/jails/{{ jail_name }} exists on {{ hostname }}
  stat:
    path=/usr/jails/{{ jail_name }}
  register: directory

- name: create jail {{ jail_name }} on {{ hostname }}
  shell: ezjail-admin create {{ jail_name }} '{{ jail_ipv4.interface }}|{{ jail_ipv4.address }},{{ jail_ipv6.interface }}|{{ jail_ipv6.address }}'
  when: jail_exists.stdout == "0" and directory.stat.exists == false
  register: jail_created
  notify: start jail

...
