---

- name: check whether jail {{ jail_name }} exists on {{ hostname }}
  shell: ezjail-admin list | grep /usr/jails/{{ jail_name | quote }} | wc -l | sed -e 's/^[ \t]*//'
  register: jail_exists

- name: check whether directory /usr/jails/{{ jail_name }} exists on {{ hostname }}
  stat:
    path=/usr/jails/{{ jail_name }}
  register: directory_exists

- name: create jail {{ jail_name }} on {{ hostname }}
  shell: ezjail-admin create {{ jail_name | quote }} '{{ jail_ipv4.interface | quote }}|{{ jail_ipv4.address | quote }},{{ jail_ipv6.interface | quote }}|{{ jail_ipv6.address | quote }}'
  when: jail_exists.stdout == "0" and directory_exists|failed and hosting != "digital_ocean"
  register: jail_created
  notify: start jail

- name: create jail {{ jail_name }} on {{ hostname }}
  shell: ezjail-admin create {{ jail_name | quote }} '{{ jail_ipv4.interface | quote }}|{{ jail_ipv4.address | quote }}'
  when: jail_exists.stdout == "0" and directory|failed and hosting == "digital_ocean"
  register: jail_created
  notify: start jail

...
