---

- name: Define Variable
  set_fact:
     jail_ssh_port: "{{ jail_ssh_port[jail_type] }}"
     jail_ipv4:
        interface: "{{ jail_ipv4.interface }}"
        address: "{{ jail_ipv4[jail_type] }}"
     jail_ipv6:
        interface: "{{ jail_ipv6.interface }}"
        address: "{{ jail_ipv6[jail_type] }}"

- include: create.yml

- include: hostname.yml

- include: config.yml

- include: rc_conf.yml

- include: sshd.yml
    host_ssh_port={{ ansible_ssh_port }}
    host_ipv4={{ jail_ipv4 }}
    host_ipv6={{ jail_ipv6 }}

- include: start.yml

...
