---

- name: set jail ip and ssh port
  set_fact:
     jail_ssh_port: "{{ jail_ssh_port[jail_type] }}"
     jail_ipv4:
        interface: "{{ jail_ipv4.interface }}"
        address: "{{ jail_ipv4[jail_type] }}"
     jail_ipv6:
        interface: "{{ jail_ipv6.interface }}"
        address: "{{ jail_ipv6[jail_type] }}"

...
