---

- name: install python and bash-static on jail {{ jail_name }} on {{ hostname }}
  shell: jexec {{ jail_name | quote }} env ASSUME_ALWAYS_YES=YES pkg install -y python bash-static
  tags:
    - install_python
    - utils

...
