---

freebsd_version: "10.3"
ansible_python_interpreter: /usr/local/bin/python2
ansible_connection: ssh
passwd_format: blf
loopback_if: lo0

pkg_repos:
  # - server_nox_local
  # - server_nox
  - FreeBSD.quarterly

packages:
  - 'ftp/wget'
  - 'lang/python2' # so Ansible can work
  - 'net/rsync'
  - 'shells/bash'
  - 'sysutils/htop'
  - 'sysutils/lsof'
  - 'sysutils/ncdu'
  - 'sysutils/pftop'

install_pkgs: yes

security_bsd_see_other_uids: 0
net_inet_tcp_blackhole: 2
net_inet_udp_blackhole: 1
net_inet_icmp_drop_redirect: 1
net_inet_ip_redirect: 0
net_inet_ip_sourceroute: 0
net_inet_ip_accept_sourceroute: 0
net_inet_icmp_bmcastecho: 0

nginx_binary_name: /usr/local/sbin/nginx
nginx_service_name: "nginx"
...
