---

ansible_python_interpreter: /usr/local/bin/python2
ansible_connection: ssh
passwd_format: blf
loopback_if: lo0

pkg_repos:
  # - server_nox_local
  - server_nox
  - FreeBSD

packages:
  - 'ftp/wget'
  - 'lang/python2' # so Ansible can work
  - 'net/rsync'
  - 'security/ca_root_nss' # so we can verify pkg repos certificates
  - 'shells/bash-static'
  - 'sysutils/lsof'
  - 'sysutils/ncdu'
  - 'sysutils/pftop'

...
