---

- name: parse pf rules
  shell: /sbin/pfctl -nf /etc/pf.conf

- name: load pf rules
  shell: /sbin/pfctl -f /etc/pf.conf

- name: full pf flush
  shell: /sbin/pfctl -F all -f /etc/pf.conf

- name: partial pf flush
  shell: /sbin/pfctl -F nat -F queue -F rules -F Sources -F info -F Tables -F osfp -f /etc/pf.conf

- name: start pf
  service: name=pf state=started

- name: start pflog
  service: name=pflog state=started

- name: enable pf
  shell: /sbin/pfctl -e

- name: disable pf
  shell: /sbin/pfctl -d

...
