---

- name: Create /etc/pf directory
  file:
    path=/etc/pf
    state=directory
    owner=0
    group=0
    mode=0755
  notify: start pf
  tags: pf

- name: check whether /etc/pf/ssh.rdr.conf exists
  stat:
    path=/etc/pf/ssh.rdr.conf
  register: ssh_rdr_conf_exists
  tags: pf

- name: Create /etc/pf/ssh.rdr.conf
  file:
    path=/etc/pf/ssh.rdr.conf
    state=touch
    owner=0
    group=0
    mode=0644
  when: ssh_rdr_conf_exists.stat.exists == false
  notify: partial pf flush
  tags: pf

- name: configure pf rules
  template: src=etc/pf.conf.j2
    dest=/etc/pf.conf
    owner=0
    group=0
    mode=0644
    validate='/sbin/pfctl -nf %s'
  notify: partial pf flush
  tags:
    - pf
    - pf_rules

- name: start pf if it is not running
  service: name=pf state=running enabled=yes
  tags: pf

...
