---

jails_if: "{{ hostvars[jail_host]['jails_if'] }}"
service_jails_base_ipv4: "{{ hostvars[jail_host]['service_jails_base_ipv4'] }}"
service_jails_base_ipv6: "{{ hostvars[jail_host]['service_jails_base_ipv6'] }}"
web_jails_base_ipv4: "{{ hostvars[jail_host]['web_jails_base_ipv4'] }}"
web_jails_base_ipv6: "{{ hostvars[jail_host]['web_jails_base_ipv6'] }}"
jails_ipv4_netmask: "{{ hostvars[jail_host]['jails_ipv4_netmask'] }}"
jails_ipv6_prefixlen: "{{ hostvars[jail_host]['jails_ipv6_prefixlen'] }}"
service_jails_base_port: "{{ hostvars[jail_host]['service_jails_base_port'] }}"
web_jails_base_port: "{{ hostvars[jail_host]['web_jails_base_port'] }}"
proto_jail_ssh_port:
  service: "{{ service_jails_base_port }}{{ jail_index }}"
  web: "{{ web_jails_base_port }}{{ jail_index }}"
proto_jail_ipv4:
  interface: "{{ jails_if }}"
  address:
    service: "{{ service_jails_base_ipv4 }}.{{ jail_index }}"
    web: "{{ web_jails_base_ipv4 }}.{{ jail_index }}"
  netmask: "{{ jails_ipv4_netmask }}"
proto_jail_ipv6:
  interface: "{{ jails_if }}"
  address:
    service: "{{ service_jails_base_ipv6 }}:{{ jail_index }}"
    web: "{{ web_jails_base_ipv6 }}:{{ jail_index }}"
  prefixlen: "{{ jails_ipv6_prefixlen }}"
ansible_ssh_port: "{{ proto_jail_ssh_port[jail_type] }}"
ipv4:
  interface: "{{ proto_jail_ipv4.interface }}"
  address: "{{ proto_jail_ipv4.address[jail_type] }}"
  netmask: "{{ proto_jail_ipv4.netmask }}"
ipv6:
  interface: "{{ proto_jail_ipv6.interface }}"
  address: "{{ proto_jail_ipv6.address[jail_type] }}"
  prefixlen: "{{ proto_jail_ipv6.prefixlen }}"

...
