---

- name: replace jail name in hostname configuration
  replace:
    dest=/usr/local/etc/ezjail/{{ jail_name }}
    regexp='^(export jail\_{{ jail_name }}\_hostname=").*(")$'
    replace='\1{{ hostname }}\2'
  notify: restart jail
  tags: set_hostname

- name: ensure jail hostname is correctly configured
  lineinfile:
    dest=/usr/local/etc/ezjail/{{ jail_name }}
    state=present
    line='export jail_{{ jail_name }}_hostname="{{ hostname }}"'
  notify: restart jail
  tags: set_hostname

...
