---

- name: add pf config to allow direct ssh connection to jail
  lineinfile:
    dest=/etc/pf/ssh.rdr.conf
    create=yes
    owner=0
    group=0
    mode=0644
    state=present
    line='rdr pass on $ext_if  inet proto {tcp udp} to ($ext_if)  port {{ jail_ssh_port }} -> {{ jail_ipv4.address }}        port {{ host_ssh_port }}'
  notify: partial pf flush
  tags: sshd_config

- name: configure jail /etc/ssh/sshd_config
  template: src=roles/freebsd/templates/etc/ssh/sshd_config.j2
    dest=/usr/jails/{{ jail_name }}/etc/ssh/sshd_config
    owner=0
    group=0
    mode=0644
  tags: sshd_config

- name: check whether jail's /root/.ssh/authorized_keys exists
  stat:
    path=/usr/jails/{{ jail_name }}/root/.ssh/authorized_keys
  register: authorized_keys_exists
  tags: sshd_config

- name: check jail and host /root/.ssh/authorized_keys are the same
  shell: diff /root/.ssh/authorized_keys /usr/jails/{{ jail_name | quote }}/root/.ssh/authorized_keys
  when: authorized_keys_exists.stat.exists == true
  register: similar_authorized_keys
  always_run: yes
  tags: sshd_config

- name: copy host's root ssh keys to jail's root
  shell: cp -Rp /root/.ssh /usr/jails/{{ jail_name | quote }}/root/
  when: authorized_keys_exists.stat.exists == false or similar_authorized_keys.stdout == ""
  tags: sshd_config

...
