---

- name: enable cloned interface
  command: /usr/sbin/sysrc cloned_interfaces="lo1"
  tags:
    - ezjail

- name: bring up cloned interface
  command: service netif cloneup
  tags:
    - ezjail

- name: install ezjail
  pkgng:
    name=sysutils/ezjail
    state=present
  register: ezjail_installed
  tags:
    - ezjail

- name: enable ezjail
  command: /usr/sbin/sysrc ezjail_enable="YES"
  tags:
    - ezjail
  notify:
    - start ezjail

- name: create base jail
  command: ezjail-admin install
  when: ezjail_installed.changed == true
  tags:
    - ezjail

...
