---

- name: set hostname
  command: hostname {{ fqdn }}

- name: persist hostname
  command: /usr/sbin/sysrc hostname={{ fqdn }}

# - include: interfaces.yml

- include: sendmail.yml

- include: pf.yml

- include: ntp.yml

- include: sshguard.yml

- include: ezjail.yml

- include: packages.yml

...
