---

- name: set hostname
  command: hostname {{ fqdn }}

- name: persist hostname
  command: /usr/sbin/sysrc hostname={{ fqdn }}

- include: interfaces.yml

- include: pf.yml

- include: ntp.yml

- include: sshguard.yml

...
