---

- name: configure pf rules
  template: src=pf.conf.j2
    dest=/etc/pf.conf owner=0 group=0 mode=0644
    validate='/sbin/pfctl -nf %s'
  tags: pf
  notify:
    - load pf rules

- name: enable pf
  command: /usr/sbin/sysrc pf_enable=YES
  tags: pf
  notify:
    - start pf

- name: enable pflog
  command: /usr/sbin/sysrc pflog_enable=YES
  tags: pf
  notify:
    - start pflog

...
