---

- name: stop sendmail
  service: name=sendmail state=stopped

- name: disable sendmail service
  command: /usr/sbin/sysrc sendmail_enable=NO

- name: disable sendmail submit
  command: /usr/sbin/sysrc sendmail_submit_enable=NO

- name: disable sendmail outbound
  command: /usr/sbin/sysrc sendmail_outbound_enable=NO

- name: disable sendmail queue
  command: /usr/sbin/sysrc sendmail_msp_queue_enable=NO

...
