---

# - set_fact:
#     ipv4: "{{ ansible_default_ipv4 }}"
#   when: "{{ if_dhcp == true and ansible_default_ipv4|length }}"
#   tags: set_properties

# - set_fact:
#     ipv6: "{{ ansible_default_ipv6 }}"
#   when: "{{ has_ipv6 and ansible_default_ipv6|length }}"
#   tags: set_properties

# - include: debug.yml
#   tags: debug

- include: pkg.yml

- include: tz.yml

- include: settings.yml

- include: users.yml

- include: rc_conf.yml

- include: sysctl_conf.yml

- include: cron.yml

- include: etc_hosts.yml

- include: sshd.yml
  vars:
    ssh_port: "{{ ansible_ssh_port }}"

- include: hostname.yml

- include: openntpd.yml
  when: has_openntpd

- include: ezjail.yml
  when: has_ezjail

- include: pf.yml
  when: has_pf

- include: jails/main.yml
  vars:
    jail: "{{ item }}"
    jail_hostname: "{{ item }}"
    jail_name: "{{ hostvars[item].jail_name }}"
    ssh_port: "{{ hostvars[item].ansible_ssh_port }}"
    ipv4: "{{ hostvars[item].ipv4 }}"
    ipv6: "{{ hostvars[item].ipv6 }}"
    sshd_config_allow_users: "{{ [users.root] }}"
  when: provides_jail_host and has_jails
  with_items: "{{ jails }}"

...
