---

- include: set_properties.yml

# - include: debug.yml

- include: pkg.yml

- include: tz.yml

- include: settings.yml

- include: users.yml

- include: rc_conf.yml

- include: sysctl_conf.yml

- include: cron.yml

- include: etc_hosts.yml

- include: sshd.yml
    host_ssh_port={{ ansible_ssh_port }}
    host_ipv4={{ ipv4 }}
    host_ipv6={{ ipv6 }}

- include: hostname.yml

- include: openntpd.yml
  when: has_openntpd

- include: ezjail.yml
  when: has_ezjail

- include: pf.yml
  when: has_pf

- include: utils.yml

...
