---

# - include: debug.yml
#   tags: debug

- include: pkg.yml

- include: tz.yml

- include: settings.yml

- include: users.yml

- include: loader_conf.yml

- include: rc_conf.yml

- include: sysctl_conf.yml

- include: cron.yml

- include: etc_hosts.yml

- include: sshd.yml
  vars:
    ssh_port: "{{ ansible_ssh_port }}"

- include: hostname.yml

- include: openntpd.yml
  when: has_openntpd

- include: ssl.yml
  tags:
    - ssl
    - letsencrypt

- include: ezjail.yml
  when: has_ezjail

- include: pf.yml
  when: has_pf

- include: storage.yml
  when: disks is defined and disks|length > 0

- include: services.yml

- include: jails/main.yml
  vars:
    jail: "{{ item }}"
    jail_hostname: "{{ hostvars[item].hostname }}"
    jail_name: "{{ hostvars[item].jail_name }}"
    ssh_port: "{{ hostvars[item].ansible_ssh_port }}"
    ext_if: "{{ hostvars[item].ext_if }}"
    sshd_config_allow_users: "{{ hostvars[item].sshd_config_allow_users }}"
    jail_mounts: "{{ hostvars[item].jail_mounts }}"
    jail_zfs_datasets: "{{ hostvars[item].jail_zfs_datasets }}"
    parameters: "{{ hostvars[item].parameters }}"
  when: provides_jail_host and has_jails
  with_items: "{{ jails }}"

...
