---

# - include: debug.yml
#   tags: debug

- include: pkg.yml

- include: tz.yml

- include: settings.yml

- include: users.yml

- include: rc_conf.yml

- include: sysctl_conf.yml

- include: cron.yml

- include: etc_hosts.yml

- include: sshd.yml
  vars:
    ssh_port: "{{ ansible_ssh_port }}"

- include: hostname.yml

- include: openntpd.yml
  when: has_openntpd

- include: ezjail.yml
  when: has_ezjail

- include: pf.yml
  when: has_pf

- include: storage.yml
  when: disks is defined and disks|length > 0

- include: jails/main.yml
  vars:
    jail: "{{ item }}"
    jail_hostname: "{{ item }}"
    jail_name: "{{ hostvars[item].jail_name }}"
    ssh_port: "{{ hostvars[item].ansible_ssh_port }}"
    ext_if: "{{ jails_if }}"
    sshd_config_allow_users: "{{ [users.root] }}"
  when: provides_jail_host and has_jails
  with_items: "{{ jails }}"

...
