---

- name: Create /etc/pf directory
  file:
    path=/etc/pf
    state=directory
    owner=0
    group=0
    mode=0755
  notify: start pf
  tags: pf

- name: configure pf rules
  template: src=etc/pf.conf.j2
    dest=/etc/pf.conf
    owner=0
    group=0
    mode=0644
    validate='/sbin/pfctl -nf %s'
  notify: partial pf flush
  tags:
    - pf
    - pf_rules

- name: configure pf jail macros
  template: src=etc/pf/jail_macros.conf.j2
    dest=/etc/pf/jail_macros.conf
    owner=0
    group=0
    mode=0644
  when: provides_jail_host
  notify: partial pf flush
  tags:
    - pf
    - pf_rules

- name: remove pf jail macros
  file:
    path=/etc/pf/jail_macros.conf
    state=absent
  when: provides_jail_host == false
  notify: partial pf flush
  tags:
    - pf
    - pf_rules

- name: configure pf jail redirections
  template: src=etc/pf/ssh.rdr.conf.j2
    dest=/etc/pf/ssh.rdr.conf
    owner=0
    group=0
    mode=0644
  when: provides_jail_host
  notify: partial pf flush
  tags:
    - pf
    - pf_rules

- name: remove pf jail redirections
  file:
    path=/etc/pf/ssh.rdr.conf
    state=absent
  when: provides_jail_host == false
  notify: partial pf flush
  tags:
    - pf
    - pf_rules

- name: start pf if it is not running
  service: name=pf state=running enabled=yes
  tags: pf

...
