---

- name: create property lists
  set_fact:
    packages: []
    services: []
  tags: set_properties

- name: populate property lists
  set_fact:
    packages: "{{ packages | union(item.packages) | unique }}"
    services: "{{ services | union(item.services) | unique }}"
  when: item.group in group_names
  with_items: "{{ properties }}"
  tags: set_properties

...
