---

- name: retrieve jail facts
  set_fact:
    features: "{{ features | union(hostvars[item].features) | unique }}"
  when: is_jail and has_jails
  with_items: "{{ jails }}"
  tags: set_properties

...
