---

- name: stop sendmail
  service: name=sendmail state=stopped
  tags: stop_sendmail

- name: check encoding in login.conf
  shell: cat /etc/login.conf | grep  -e ':lang={{ host_locale | quote }}:$' | wc -l | sed -e 's/^[ \t]*//'
  register: encoding_updated
  changed_when: false
  always_run: yes
  tags: encoding

- set_fact:
    mkdb_file: /etc/login.conf
  changed_when: false
  tags:
    - encoding
    - passwd_format

- name: change charset
  patch: >
    src=files/usr/local/share/patches/etc_login_conf_encoding.patch.j2
    dest=/etc/login.conf
  when: encoding_updated.stdout == "0"
  notify: rebuild db
  tags: encoding

- name: update charset in login.conf
  lineinfile:
    dest=/etc/login.conf
    state=present
    regexp="^(.*)<HOST_CHARSET>(.*)$"
    line="\1{{ host_charset }}\2"
    backrefs=yes
  when: encoding_updated.stdout == "0"
  notify: rebuild db
  tags: encoding

- name: update locale in login.conf
  lineinfile:
    dest=/etc/login.conf
    state=present
    regexp="^(.*)<HOST_LOCALE>(.*)$"
    line="\1{{ host_locale }}\2"
    backrefs=yes
  when: encoding_updated.stdout == "0"
  notify: rebuild db
  tags: encoding

- name: update passwd format in /etc/login.conf
  lineinfile:
    dest=/etc/login.conf
    state=present
    regexp="^\t(.*)passwd_format=[a-z0-9]*(.*)$"
    line="\t\1passwd_format={{ passwd_format }}\2"
    backrefs=yes
  notify: rebuild db
  tags: passwd_format

...
