---

- name: stop sendmail
  service: name=sendmail state=stopped
  tags: stop_sendmail

- name: check encoding in login.conf
  shell: cat /etc/login.conf | grep  -e ':lang={{ host_locale | quote }}:$' | wc -l | sed -e 's/^[ \t]*//'
  register: encoding_updated
  changed_when: false
  always_run: yes
  tags: encoding

- set_fact:
    mkdb_file: /etc/login.conf
  changed_when: false
  tags:
    - encoding
    - passwd_format

- name: upload patch file
  template: src=files/usr/local/share/patches/etc_login_conf_encoding.patch.j2
    dest=/tmp/etc_login_conf_encoding.patch
    owner=0
    group=0
    mode=0644
  when: encoding_updated.stdout == "0"
  register: encoding_patch_uploaded
  tags: encoding

- name: change charset
  patch: >
    src=/tmp/etc_login_conf_encoding.patch
    dest=/etc/login.conf
    remote_src=yes
  when: encoding_updated.stdout == "0"
  notify: rebuild db
  tags: encoding

- name: delete patch file
  file: path=/tmp/etc_login_conf_encoding.patch
    state=absent
  when: encoding_patch_uploaded.changed == true
  tags: encoding

- name: update passwd format in /etc/login.conf
  lineinfile:
    dest=/etc/login.conf
    state=present
    regexp="^\t(.*)passwd_format=[a-z0-9]*(.*)$"
    line="\t\1passwd_format={{ passwd_format }}\2"
    backrefs=yes
  notify: rebuild db
  tags: passwd_format

...
