---

- name: configure /etc/ssh/sshd_config
  template: src=etc/ssh/sshd_config.j2
    dest=/etc/ssh/sshd_config
    owner=0
    group=0
    mode=0644
  notify: reload sshd
  tags: sshd_config

- name: authorized keys deployment
  authorized_key: 
    user={{ item.0.name }}
    key='{{ lookup('file', item.1) }}'
    state=present
  with_subelements:
    - sshd_config_allow_users | default([])
    - pubkeys
  register: authkeys_set
  tags: sshd_config

- name: checks whether jail ssh port is amongst ssh ports in pf
  shell: "cat /etc/pf.conf | grep -E '^(.*ssh.*{[0-9 ]*){{ ansible_ssh_port }}([0-9 ]*}.*)$' | wc -l | sed -e 's/^[ \t]*//'"
  register: ssh_port_registered
  changed_when: false
  always_run: yes
  when: host_type == "jailed_host"
  delegate_to: "{{ jail_host }}"
  tags: sshd_config

- name: add jail ssh port to ssh ports in pf
  lineinfile:
    dest=/etc/pf.conf
    create=yes
    state=present
    regexp="^(.*ssh.*\{[0-9 ]*)( \}.*)$"
    line="\1 {{ ansible_ssh_port }}\2"
    backrefs=yes
  when: host_type == "jailed_host" and ssh_port_registered.stdout == "0"
  delegate_to: "{{ jail_host }}"
  register: ssh_port_added
  tags: sshd_config

- name: flush pf
  shell: /sbin/pfctl -F nat -F queue -F rules -F Sources -F info -F Tables -F osfp -f /etc/pf.conf
  when: ssh_port_added.changed == true
  delegate_to: "{{ jail_host }}"
  tags: sshd_config

- name: add pf config to allow direct ssh connection to jail
  lineinfile:
    dest=/etc/pf/ssh.rdr.conf
    create=yes
    owner=0
    group=0
    mode=0644
    state=present
    line='rdr pass on $ext_if  inet proto {tcp udp} to ($ext_if)  port {{ host_ssh_port }} -> {{ ipv4.address }}        port {{ host_ssh_port }}'
  when: host_type == "jailed_host"
  delegate_to: "{{ jail_host }}"
  register: ssh_rdr_added
  notify: partial pf flush
  tags: sshd_config

- name: flush pf
  shell: /sbin/pfctl -F nat -F queue -F rules -F Sources -F info -F Tables -F osfp -f /etc/pf.conf
  when: ssh_rdr_added.changed == true
  delegate_to: "{{ jail_host }}"
  tags: sshd_config

...
