---

- name: configure /etc/ssh/sshd_config
  template: src=etc/ssh/sshd_config.j2
    dest=/etc/ssh/sshd_config
    owner=0
    group=0
    mode=0644
  notify: reload sshd
  tags: sshd_config

- name: authorized keys deployment
  authorized_key: 
    user={{ item.0.name }}
    key='{{ lookup('file', item.1) }}'
    state=present
    manage_dir=yes
  with_subelements:
    - '{{ hostvars[hostname].sshd_config_allow_users | default([]) }}'
    - pubkeys
  register: authkeys_set
  no_log: "{{ hide_logs }}"
  tags: sshd_config

...
