---

- name: configure smartd with per-disk params
  template: src=usr/local/etc/smartd.conf.j2
    dest=/usr/local/etc/smartd.conf
    owner=0
    group=0
    mode=0640
  when: smartd_params is defined and smartd_params|length > 0
  notify: restart smartd
  tags:
    - smartd
    - storage

- name: retrieve drive data
  shell: "camcontrol identify {{ item | quote }}"
  with_items: "{{ disks }}"
  register: drive_data
  changed_when: false
  no_log: true
  tags:
    - storage
    - backup_storage_data

- name: store drive data locally
  local_action: 'file state=directory path="./host_data/{{ hostname }}/{{ item.item[5:] }}" follow=true'
  with_items: '{{ drive_data.results }}'
  when: drive_data is defined
  no_log: true
  tags:
    - storage
    - backup_storage_data

- name: store drive data locally
  local_action: 'file state=file content="{{ item.stdout_lines|join(\"\\n\") }}" path="./host_data/{{ hostname }}/{{ item.item[5:] }}/drive_data.txt" follow=true'
  with_items: '{{ drive_data.results }}'
  when: drive_data is defined
  no_log: true
  tags:
    - storage
    - backup_storage_data

...
