---

- name: configure smartd with per-disk params
  template: src=usr/local/etc/smartd.conf.j2
    dest=/usr/local/etc/smartd.conf
    owner=0
    group=0
    mode=0640
  when: smartd_params is defined and smartd_params|length > 0
  notify: restart smartd
  tags:
    - storage
    - smartd

- name: check whether ../ansible_variables/host_data/{{ hostname }}_storage_data.txt exists
  local_action: 'stat path=../ansible_variables/host_data/{{ hostname }}_storage_data.txt'
  always_run: yes
  register: storage_data_file
  tags:
    - storage
    - collect_storage_data

- name: upload collect_storage_data.sh script
  template: src=usr/local/share/collect_storage_data.sh.j2
    dest=/usr/local/share/collect_storage_data.sh
    owner=0
    group=0
    mode=0755
  when: storage_data_file.stat.exists == false
  tags:
    - storage
    - collect_storage_data

- name: collect storage data
  shell: "/usr/local/share/collect_storage_data.sh > /tmp/{{ hostname }}_storage_data.txt"
  changed_when: false
  when: storage_data_file.stat.exists == false
  tags:
    - storage
    - collect_storage_data

- name: retrieve collected storage data
  synchronize:
    src=/tmp/{{ hostname }}_storage_data.txt
    dest=../../ansible_variables/host_data/{{ hostname }}_storage_data.txt
    mode=pull
    checksum=yes
    rsync_path="/usr/local/bin/rsync"
  when: storage_data_file.stat.exists == false
  tags:
    - storage
    - collect_storage_data

...
