---

# db
- name: rebuild db
  shell: /usr/bin/cap_mkdb {{ mkdb_file }}

# openntpd
- name: start openntpd
  service: name=openntpd state=started

- name: restart openntpd
  service: name=openntpd state=restarted

# sshd
- name: reload sshd
  service: name=sshd state=reloaded

# sshguard
- name: restart sshguard
  service: name=sshguard state=restarted

# ezjail
- name: start ezjail
  service: name=ezjail state=started

- name: restart ezjail
  service: name=ezjail state=restarted

- name: start jail
  shell: ezjail-admin start {{ jail_name | quote }}

- name: restart jail
  shell: ezjail-admin restart {{ jail_name | quote }}

# nginx
- name: start nginx
  shell: service nginx start

- name: restart nginx
  shell: service nginx restart

- name: reload nginx
  shell: service nginx reload

# pf
- name: parse pf rules
  shell: /sbin/pfctl -nf /etc/pf.conf

- name: load pf rules
  shell: /sbin/pfctl -f /etc/pf.conf

- name: full pf flush
  shell: /sbin/pfctl -F all -f /etc/pf.conf

- name: partial pf flush
  shell: /sbin/pfctl -F nat -F queue -F rules -F Sources -F info -F Tables -F osfp -f /etc/pf.conf
  notify:
    - restart jail

- name: start pf
  service: name=pf state=started

- name: start pflog
  service: name=pflog state=started

- name: enable pf
  shell: /sbin/pfctl -e

- name: disable pf
  shell: /sbin/pfctl -d

# system
- name: reboot
  shell: shutdown -r now
...
