---

# terminate ssl, both for ipv4 and 6
# set hsts
# redirect let's encrypt traffic to letsencrypt jail
# redirect all remaining http traffic to https

- include: logs.yml
  tags:
    - nginx_config
    - nginx_logs

- include: ssl.yml
  tags:
    - nginx_config
    - ssl

- include: nginx_conf.yml
  tags:
    - nginx_config
    - nginx.conf

- include: site_conf.yml
  tags:
    - nginx_config
    - site.conf

...
