---

hostname: droplet01.docbase.net
timezone: Europe/Amsterdam
os: freebsd
hosting: digital_ocean
jails:
  - rproxy02.docbase.net

features:
  - bsdstats
  - ezjail
  - ipv6
  # - linuxulator
  - openntpd
  - pf
  # - smartd
  - sshd
  - sshguard
  # - zfs

installed_users:
  - "{{ users.root }}"
  - "{{ users.user1 }}"

sshd_config_allow_users:
    - "{{ users.root }}"
    - "{{ users.user1 }}"

droplet_name: droplet01
droplet_size: 512mb
droplet_image: freebsd-10-2-x64
droplet_region: ams2

ipv4:
  interface: vtnet0
  address: 111.222.333.444
  netmask: 255.255.255.0
  gateway: 111.222.333.1

ipv6:
  interface: vtnet0
  address: AAAA:BBBB:0000:0000:0000:0000:0000:9999
  prefixlen: 64
  gateway: AAAA:BBBB:0000:0000:0000:0000:0000:0001

ansible_ssh_port: 123

...
