---

hostname: letsencrypt01.docbase.net
timezone: Europe/Amsterdam
os: freebsd

installed_users:
  - "{{ users.root }}"

sshd_config_allow_users:
    - "{{ users.root }}"

jail_name: letsencrypt01
jail_index: 2
jail_type: service
jail_autorun: true

features:
  - http_proxy
  - letsencrypt
  - sshd

requires: [reverse_proxy]

# temporary settings

...
