---

hostname: letsencrypt01.docbase.net
timezone: Europe/Berlin
os: freebsd

installed_users:
  - "{{ users.root }}"

sshd_config_allow_users:
  - "{{ users.root }}"

jail_name: letsencrypt01
jail_index: 2
jail_type: service
jail_autorun: true
jail_mounts:
  - { 'mount': '/usr/jails/basejail', 'on': '/usr/jails/letsencrypt01/basejail', 'fs': 'nullfs', 'r': 'ro' }

features:
  - http_proxy
  - letsencrypt
  - sshd

requires: [reverse_proxy]

pkg_repos:
  - FreeBSD.latest

# temporary settings

...
