---

hostname: mail02.example.net
timezone: Europe/Amsterdam
os: freebsd
type: iredmail
hosting: "{{ hostvars[jail_host]['hosting'] }}"
host_type: jailed_host

jail_name: iredmail
jail_host: droplet01.example.net
jail_index: 1
jail_type: service
jail_autorun: true

installed_users:
  - "{{ users.root }}"
  - "{{ users.user1 }}"

...
