---

hostname: mail01.docbase.net
timezone: Europe/Berlin
os: freebsd

installed_users:
  - "{{ users.root }}"

sshd_config_allow_users:
  - "{{ users.root }}"

jail_name: mail01
jail_index: 10
jail_type: service
jail_autorun: true
jail_mounts:
  - { 'mount': '/usr/jails/basejail', 'on': '/usr/jails/mail01/basejail', 'fs': 'nullfs', 'r': 'ro' }
  - { 'mount': '/var/mail/vmail01', 'on': '/usr/jails/mail01/var/vmail', 'fs': 'nullfs', 'r': 'rw', 'owner': '2000', 'group': '2000', 'mode': '0775' }

nginx_http_config_worker_processes: 2
nginx_http_config_keepalive_timeout: 600

sites:
  - name: mail
    fqdns: mail.docbase.net mail01.docbase.net
    redirection:
      permanent: true
      https: true
    root: /usr/local/www/apache24/data
    allow_iframe: true
    sniff_content: true
    upstreams:
      - name: php_workers
        servers:
          - unix:/var/run/php-fpm.socket
        keepalive: 600
    includes:
      - /usr/local/etc/nginx/templates/roundcube.tmpl
      - /usr/local/etc/nginx/templates/php-catchall.tmpl
      - /usr/local/etc/nginx/templates/iredadmin.tmpl
      - /usr/local/etc/nginx/templates/sogo.tmpl
      - /usr/local/etc/nginx/templates/misc.tmpl

features:
  - amavis
  - clamav
  - dovecot
  - http_proxied
  - iredmail
  - mail
  - memcached
  - mysql_client
  - mysql_server
  - nginx
  - php
  - postfix
  - slapd
  - sogo
  - sshd
  - uwsgi

requires: [reverse_proxy, letsencrypt]

# temporary settings
hide_logs: false
install_pkgs: no

...
