---

hostname: mail02.docbase.net
timezone: Europe/Amsterdam
os: freebsd

installed_users:
  - "{{ users.root }}"

sshd_config_allow_users:
    - "{{ users.root }}"

jail_name: iredmail
jail_index: 9
jail_type: service
jail_autorun: true

features:
  - iredmail
  - mail_server
  - sshd

requires: [reverse_proxy]

...
