---

hostname: mysql02.docbase.net
timezone: Europe/Amsterdam
os: freebsd
type: mysql
hosting: "{{ hostvars[jail_host]['hosting'] }}"
host_type: jailed_host

jail_name: mysql
jail_index: 2
jail_type: service
jail_autorun: true

installed_users:
  - "{{ users.root }}"
  - "{{ users.user1 }}"

sshd_config_allow_users:
  - "{{ users.root }}"
  - "{{ users.user1 }}"

...
