---

hostname: rproxy01.docbase.net
timezone: Europe/Berlin
os: freebsd

installed_users:
  - "{{ users.root }}"

sshd_config_allow_users:
    - "{{ users.root }}"

jail_name: rproxy01
jail_index: 1
jail_type: service
jail_autorun: true

features:
  - ipv6
  - nginx_proxy
  - sshd

# temporary settings

...
