---

- name: Create endpoint abi directories
  file:
    path=/usr/local/poudriere/endpoints/{{ item.1 }}
    state=directory
    owner=0
    group=0
    mode=0755
  with_subelements:
    - "{{ poudriere_pkg_endpoints }}"
    - abis

- name: Create links from pkg endpoints to package repos
  file:
    state=link
    src=/usr/local/poudriere/data/packages/{{ item.0.dir }}
    dest=/usr/local/poudriere/endpoints/{{ item.1 }}/{{ item.0.alias }}
  with_subelements:
    - "{{ poudriere_pkg_endpoints }}"
    - abis

...
