---

- name: set timezone
  command: /usr/sbin/tzsetup -s {{ timezone }}
  tags: ntp
  notify:
    - restart ntpd

- name: enable ntp
  command: /usr/sbin/sysrc ntpd_enable=YES
  tags: ntp

- name: ntp sync on start
  command: /usr/sbin/sysrc ntpd_sync_on_start=YES
  tags: ntp

...
