---

- hosts: localhost
  gather_facts: no
  vars_files:
    - 'host_vars/{{ hostname }}.yml'
  roles:
    - do_new_droplet

- hosts: new_droplets
  gather_facts: no
  vars_files:
    - 'host_vars/{{ hostname }}.yml'
  roles:
    - { role: do_free_droplet, ansible_user: freebsd, sudo: yes }

- hosts: new_droplets
  gather_facts: yes
  vars_files:
    - 'host_vars/{{ hostname }}.yml'
  roles:
    - { role: f500.dumpall, dumpall_host_destination: 'examine/{{ droplet_name }}/' }

...
