---

- name: set cloned interfaces
  command: /usr/sbin/sysrc cloned_interfaces="${cloned_interfaces} {{ jails_if }}"

- name: activate ipv6 on all interfaces
  command: /usr/sbin/sysrc ipv6_activate_all_interfaces="YES"

- name: enable IPv policy control
  command: /usr/sbin/sysrc ip6addrctl_enable="YES"

- name: set IPv policy control to prefer IPv4
  command: /usr/sbin/sysrc ip6addrctl_policy="ipv4_prefer"

...
