---

- name: copy user files
  copy:
    src=files/users/{{ item.item.name }}/
    dest={{ item.stdout }}
    owner={{ item.item.uid }}
    group={{ item.item.gid }}
    mode=0644
  with_items: users_homedirs.results
  changed_when: false
  tags:
    - config_user
    - user_files

- name: check .history existence
  stat: path={{ item.stdout }}/.history
  with_items: users_homedirs.results
  register: history_file_exists
  tags:
    - config_user
    - user_files

- name: enforce .history permissions
  file:
    state=file
    path={{ item.stat.path }}
    owner={{ item.item.item.uid }}
    group={{ item.item.item.gid }}
    mode=0600
  with_items: history_file_exists.results
  when: item.stat.exists == true
  register: enforce_user_history_permissions
  tags:
    - config_user
    - user_files

- name: check .bash_history existence
  stat: path={{ item.stdout }}/.bash_history
  with_items: users_homedirs.results
  register: bash_history_file_exists
  tags:
    - config_user
    - user_files

- name: enforce .bash_history permissions
  file:
    state=file
    path={{ item.stat.path }}
    owner={{ item.item.item.uid }}
    group={{ item.item.item.gid }}
    mode=0600
  with_items: bash_history_file_exists.results
  when: item.stat.exists == true
  register: enforce_user_bash_history_permissions
  tags:
    - config_user
    - user_files

- name: check .mysql_history existence
  stat: path={{ item.stdout }}/.mysql_history
  with_items: users_homedirs.results
  register: mysql_history_file_exists
  tags:
    - config_user
    - user_files

- name: enforce .mysql_history permissions
  file:
    state=file
    path={{ item.stat.path }}
    owner={{ item.item.item.uid }}
    group={{ item.item.item.gid }}
    mode=0600
  with_items: mysql_history_file_exists.results
  when: item.stat.exists == true
  register: enforce_user_mysql_history_permissions
  tags:
    - config_user
    - user_files

- name: check .psql_history existence
  stat: path={{ item.stdout }}/.psql_history
  with_items: users_homedirs.results
  register: psql_history_file_exists
  tags:
    - config_user
    - user_files

- name: enforce .psql_history permissions
  file:
    state=file
    path={{ item.stat.path }}
    owner={{ item.item.item.uid }}
    group={{ item.item.item.gid }}
    mode=0600
  with_items: psql_history_file_exists.results
  when: item.stat.exists == true
  register: enforce_user_psql_history_permissions
  tags:
    - config_user
    - user_files

- name: check .rhosts existence
  stat: path={{ item.stdout }}/.rhosts
  with_items: users_homedirs.results
  register: rhosts_file_exists
  tags:
    - config_user
    - user_files

- name: enforce .rhosts permissions
  file:
    state=file
    path={{ item.stat.path }}
    owner={{ item.item.item.uid }}
    group={{ item.item.item.gid }}
    mode=0644
  with_items: rhosts_file_exists.results
  when: item.stat.exists == true
  register: enforce_user_rhosts_permissions
  tags:
    - config_user
    - user_files