---

- name: install python
  pkgng: name=python state=present
  tags: utils

- name: install bash-static
  pkgng: name=bash-static state=present
  tags: utils

- name: install rsync
  pkgng: name=rsync state=present
  tags: utils

...
