---

- name: check jail's autorun status
  stat:
    path=/usr/local/etc/ezjail/{{ jail_name }}.norun
  register: jail_norun

- name: set jail autorun to 'run'
  shell: ezjail-admin config -r run {{ jail_name | quote }}
  changed_when: false
  always_run: yes
  when:  hostvars[jail].jail_autorun and jail_norun.stat.exists == true

- name: set jail autorun to 'norun'
  shell: ezjail-admin config -r norun {{ jail_name | quote }}
  changed_when: false
  always_run: yes
  when: not hostvars[jail].jail_autorun and jail_norun.stat.exists == false

- name: check whether jail's /etc/resolv.conf exists
  stat:
    path=/usr/jails/{{ jail_name }}/etc/resolv.conf
  register: etc_resolv_conf_exists

- name: check jail and host /etc/resolv.conf are the same
  shell: diff /etc/resolv.conf /usr/jails/{{ jail_name | quote }}/etc/resolv.conf
  when: etc_resolv_conf_exists.stat.exists == true
  changed_when: false
  always_run: yes
  register: similar_etc_resolv_conf

- name: copy host's /etc/resolv.conf to jail
  shell: cp -p /etc/resolv.conf /usr/jails/{{ jail_name | quote }}/etc/
  changed_when: false
  always_run: yes
  when: etc_resolv_conf_exists.stat.exists == false or similar_etc_resolv_conf.stdout == ""

...
