---

- name: check whether jail exists
  shell: ezjail-admin list | grep -e "/usr/jails/{{ jail_name | quote }}$" | wc -l | sed -e 's/^[ \t]*//'
  register: jail_exists
  changed_when: false
  always_run: yes

- name: check whether directory /usr/jails/--jail_name-- exists
  stat: path=/usr/jails/{{ jail_name }}
  register: jail_directory_exists

- name: create jail
  shell: ezjail-admin create {{ jail_name | quote }} '{% for ip in hostvars[jail].ext_if.ipv4s + hostvars[jail].ext_if.ipv6s %}{{ hostvars[jail].ext_if.name | quote }}|{{ ip.address | quote }}{% endfor %}{% for ip in hostvars[jail].lo_if.ipv4s + hostvars[jail].lo_if.ipv6s %},{{ hostvars[jail].lo_if.name | quote }}|{{ ip.address | quote }}{% endfor %}'
  when: jail_exists.stdout == "0" and jail_directory_exists.stat.exists == false
  notify: start jail
  register: jail_created
  tags: create_jails

...
