---

- name: check whether bash is installed on jail
  stat:
    path=/usr/jails/{{ jail_name }}/usr/local/bin/bash
  register: bash_exists
  tags: install_bash

- name: check whether python is installed on jail
  stat:
    path=/usr/jails/{{ jail_name }}/usr/local/bin/python
  register: python_exists
  tags: install_python

- name: check whether ca_root_nss is installed on jail
  stat:
    path=/usr/jails/{{ jail_name }}/usr/local/share/certs/ca-root-nss.crt
  register: ca_root_nss_exists
  tags: install_ca_root_nss
  
- name: install bash-static, python and ca_root_nss on jail
  shell: jexec {{ jail_name | quote }} env ASSUME_ALWAYS_YES=YES pkg install -y python bash-static security/ca_root_nss
  when: bash_exists.stat.exists == false or python_exists.stat.exists == false or ca_root_nss_exists.stat.exists == false
  tags:
    - install_bash
    - install_python
    - install_ca_root_nss

...
