---

- hosts: all
  connection: local
  gather_facts: no
  tasks:
    - group_by: key={{ os }}
    - group_by: key={{ hosting }}
  tags: set_properties

- hosts: first_class_hosts
  become: yes
  gather_facts: no
  roles:
    - freebsd

...
