---

- hosts: all
  connection: local
  gather_facts: no
  tasks:
    - group_by: key={{ os }}
    - group_by: key={{ hosting }}
  tags: set_properties

- hosts: nginx_proxy, nginx
  become: yes
  gather_facts: no
  roles:
    - nginx
  tags: nginx

...
