---

- hosts: all
  connection: local
  gather_facts: no
  tasks:
    - group_by: key={{ os }}
    - group_by: key={{ hosting }}
  tags: set_properties

- hosts: poudriere
  become: yes
  gather_facts: no
  roles:
    - poudriere
  tags: poudriere

...
