---

- hosts: all
  connection: local
  gather_facts: no
  tasks:
    - group_by: key={{ os }}
    - group_by: key={{ type }}
    - group_by: key={{ hosting }}
    - group_by: key={{ host_type }}
  tags: set_properties

- hosts: all
  sudo: yes
  gather_facts: no
  roles:
    - freebsd

...
