---

- hosts: all
  connection: local
  gather_facts: no
  tasks:
    - group_by: key={{ os }}
    - group_by: key={{ hosting }}
  tags: set_properties

- hosts: first_class_hosts
  become: yes
  gather_facts: no
  roles:
    - freebsd

- hosts: jails
  become: yes
  gather_facts: no
  roles:
    - freebsd

- hosts: poudriere
  become: yes
  gather_facts: no
  roles:
    - poudriere
  tags: poudriere

- hosts: nginx_proxy, nginx
  become: yes
  gather_facts: no
  roles:
    - nginx
  tags: nginx

...
