---

- name: enable cloned interface
  command: /usr/sbin/sysrc cloned_interfaces="{{ jails_if }}"
  tags:
    - ezjail

- name: bring up cloned interface
  command: service netif cloneup
  tags:
    - ezjail

- name: make sure the cloned interface has an ip address
  command: ifconfig "{{ jails_if }}" inet {{ lo_base_ip }}.1 netmask 255.255.255.0
  tags:
    - ezjail

- name: install ezjail
  pkgng: name=sysutils/ezjail state=present
  register: ezjail_installed
  tags:
    - ezjail

- name: enable ezjail
  command: /usr/sbin/sysrc ezjail_enable="YES"
  tags:
    - ezjail

- name: create base jail
  command: ezjail-admin install
  when: ezjail_installed.changed == true
  tags:
    - ezjail
  notify:
    - start ezjail

...
