---

- name: check the hostname
  shell: hostname
  register: hostname_value
  changed_when: false
  tags: set_hostname

- name: set hostname
  command: hostname {{ hostname | quote }}
  when: hostname_value.stdout != hostname
  tags: set_hostname

- name: check the hostname in /etc/rc.conf
  shell: cat /etc/rc.conf | grep {{ hostname | quote }} | wc -l | sed -e 's/^[ \t]*//'
  register: hostname_present
  changed_when: false
  tags: set_hostname

- name: persist hostname on /etc/rc.conf
  command: /usr/sbin/sysrc hostname="{{ hostname | quote }}"
  when: hostname_present.stdout == "0"
  tags: set_hostname

...
