---

- name: Create /etc/pf directory
  file:
    path=/etc/pf
    state=directory
    owner=0
    group=0
    mode=0755
  notify:
    - start pf

- name: check whether /etc/pf/ssh.rdr.conf exists
  stat:
    path=/etc/pf/ssh.rdr.conf
  register: ssh_rdr_conf_exists

- name: Create /etc/pf/ssh.rdr.conf
  file:
    path=/etc/pf/ssh.rdr.conf
    state=touch
    owner=0
    group=0
    mode=0644
  when: ssh_rdr_conf_exists|failed
  notify:
    - partial pf flush

- name: configure pf rules
  template: src=etc/pf.conf.j2
    dest=/etc/pf.conf
    owner=0
    group=0
    mode=0644
    validate='/sbin/pfctl -nf %s'
  tags: pf
  notify:
    - partial pf flush

...
